version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.5-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password123
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics","-q","ping" ]
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

volumes:
  rabbitmq_data:
    driver: local
